### PR TITLE
支持仅配置需自定义的配置项

### PR DESCRIPTION
**Pull request by luohuaizhi**
Allow partial config to be merged with default config 支持仅配置需自定义的配置项

### CODE REVIEW

**Comment by billyrrr** [comment]
这个方案可能会对新用户造成混淆，在末尾新建一个’merge_config’ kwarg 是不是更好一些？或者其他名字也可以 

This may cause confusion in new users. How about adding an additional ‘merge_config’ kwarg at the end of the list? You may also come up with a better name.

**Comment by luohuaizhi** [comment]
> 这个方案可能会对新用户造成混淆，在末尾新建一个’merge_config’ kwarg 是不是更好一些？或者其他名字也可以
> 
> This may cause confusion in new users. How about adding an additional ‘merge_config’ kwarg at the end of the list? You may also come up with a better name.

新用户使用默认配置没有影响，这是进阶用户才会使用到的功能

**Comment by joeystevens00** [comment]
I find the existing functionality confusing and this PR to be an improvement.

This should be valid but it's not:
```
swagger = Swagger(app,  config={
    "swagger_ui": False,
})
```

Instead users have to provide something like
```
swagger = Swagger(app,  config={
    "headers": [
    ],
    "specs": [
        {
            "endpoint": 'apispec_1',
            "route": '/apispec_1.json',
            "rule_filter": lambda rule: True,  # all in
            "model_filter": lambda tag: True,  # all in
        }
    ],
    "static_url_path": "/flasgger_static",
    "swagger_ui": False,
})
```

**Comment by billyrrr** [comment]
Since we have existing users expecting ```config``` to entirely replace ```self.DEFAULT_CONFIG.copy()```, this change have the potential to create unexpected behaviors. It is nevertheless true that current behavior can be confusing. I think that a pull request with a different field name for this use case would be helpful. For this keyword argument, it is better to default to ```None``` and be initialized in function body to a dictionary out of convention. Additionally, a warning may be added in the documentations to warn the users that ```config``` replaces rather than amends ```self.DEFAULT_CONFIG.copy()```. What do you think? @luohuaizhi @joeystevens00 

由于我们已有用户希望```config```能够完全替代```self.DEFAULT_CONFIG.copy()```，因此此更改有可能产生意外行为。 但是，当前的行为确实令人困惑。 我认为对于此用例，使用不同字段名称的PR会有所帮助。 对于这个关键字参数，最好默认为```None``并在函数体中初始化为```dict()```以此符合约定。 另外，最好在文档中添加警告以警告用户config代替而不是修改```self.DEFAULT_CONFIG.copy()```。你怎么看？

**Comment by billyrrr** [comment]
A "merge=False" keyword argument will be added to the `__init__` argument list and, when "merge=True", the behavior will be as defined in this commit. I will rebase and merge this commit with the above modification soon.

**Comment by billyrrr** [comment]
Merged in 63ed0ca5aef656105b3a6e39f07b7c259d3c4768 with modifications. Thank you for your contribution!

**Pull request closed without merging**
