### PR TITLE
Make new contributor easier to test their code by simplify test command in ReadMe.md and Makefile. ( Failed. Changing ReadMe.md will break CI )

### PR DESCRIPTION
**Pull request by Lounarok**
Hi,

I create this pull request because I stumble through `make test` and found multiple issues.
UntilI found there is a `requirement-dev.txt` after 30 minutes...ooops.

Add a comment [here](https://github.com/flasgger/flasgger/issues/105#issuecomment-963240207) but it's not enough.

So I change the Makefile and ReadMe.md for new contributors, but travis CI breaks. I removed the change of makefile

However travis CI still failed..

### CODE REVIEW

**Comment by Lounarok** [comment]
Hi, I think travis CI has some issue with the test because what I changed is just ReadMe.md which should not break tests...

**Comment by Lounarok** [comment]
I don't know why changing the ReadMe.md breaks the CI... but I will close this pr. Just leaving the history about it.

**Comment by billyrrr** [comment]
I'll look into it

**Comment by Lounarok** [comment]
I'd like to add some vscode settings config to the trunk. It will let new contributors easier to run the tests.
Some of the tests cannot be directly run by vscode test framework..

**Pull request closed without merging**
