### PR TITLE
Fix openapi3 request parse validation

### PR DESCRIPTION
**Pull request by Lounarok**
This is a fix for #357.
It's a problem caused by extracting schemas in a location which is changed by openapi3.

This is a PR depends on #504 but it's not very hard to merge without it.
Only last two commits are related to this PR
```
Fix request parse for openapi3. 8e731d5
Add tests for parse openapi3 request 5d16c30
```
Please let me know your decision.

### CODE REVIEW

**Comment by Lounarok** [comment]
I got the same issues like #503.
Some test build are failed in `pip intsall` with weird errors..

```
Processing dependencies for flasgger-package==0.0.1
error: zipp 0.5.1 is installed but zipp>=3.1.0; python_version < "3.10" is required by {'importlib-resources'}
Makefile:11: recipe for target 'flasgger_package' failed
make: *** [flasgger_package] Error 1
The command "make test" exited with 2.
```

**Comment by Lounarok** [comment]
@billyrrr 
I think previous CI build failed is because of pip 20.3's bug.
You may compare the [success test](https://app.travis-ci.com/github/flasgger/flasgger/jobs/548997981) and the [failed test](https://app.travis-ci.com/github/flasgger/flasgger/jobs/548030749).

I found the difference is pip version and it's why my PR #503 failed while only ReadMe.md is modified.
I added #503's changes into this branch. Please let me know if you think they should be separate into two different PRs.

**Comment by billyrrr** [comment]
Thank you for these improvements. I have merged the code without a review. Some modifications and fixes may be made to these features before release over pypi.

**Comment by Lounarok** [comment]
Hi @billyrrr, thanks for the merge. About the fixes or modifications, do you find something need to fix immediately or refer to some potential bugs? 
If it's the existing bugs, please let me know the issue number.
If it's the latter, I'll help for fixing it.

**Comment by mcclayton** [comment]
HI @billyrrr and @Lounarok, I'd love to see this make its way to a published release as I am currently trying to get our swagger to be OpenAPI 3.0 compliant, and would love to be able to use @Lounarok's changes. Thank you both for your contributions!

**Comment by Lounarok** [comment]
@mcclayton I had this issue as well. 
I did a [pypi](https://pypi.org/project/louFlasgger/) for this change until new official version is released.

**Comment by mcclayton** [comment]
Thanks @Lounarok 🎉 
I'll use this for testing, but would still love to be able to pin to an official release once one is published.

**Pull request merged**
